version: "3.7"
services:
  web:
    build: .
    volumes:
        - ./loan_system/var/www/html
    ports:
        - 80:80
  db:
        image: mysql
        volumes: 
            - ./db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: loan_system
        ports: 
            - 3306:3306
    